### PR TITLE
Dev/localities geocode

### LINKED ISSUE #1: Typo on Distance request parameter
On distance, the route api parameters are `origin`, `destination` (singular) and not `origins`, `destinations` (plural).
Check the [docs](https://developers.woosmap.com/api-reference#operation/getRoute)

### PR DESCRIPTION
**Pull request by cdartnell-wgs**
# Description
## Issue

closes Woosmap/Localities#408
## What

_Added a new endpoint, fixed a bug... etc._

## How

_I used this library to add this to make that better_

## Related PRs

# Testing
- [ ] Unit Tests cover the change
- [ ] Smoke Tests cover the change  
_If one of the above boxes is not ticked please explain why._

## Steps to Test or Reproduce
- `bender test`

# Ops
## Deploy
- [ ] This is a standard deployment  
_If this box is not ticked please explain why and detail the steps to deploy._

## Migrations

Yes | No

### CODE REVIEW

**Comment by cdartnell-wgs** [comment]
PR preview: [](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/Woosmap/openapi-specification/dev/localities-geocode/dist/woosmap-openapi3.json)

**Review by gaelsimon — APPROVED** [review]

**Pull request merged**
