### PR TITLE
localities_details: finish deprecating addresses_per_page and page parameter

### PR DESCRIPTION
**Pull request by cdartnell-wgs**
# Description
## Issue

closes Woosmap/localities#481

## What

added the 2 params to display a deprecation message

## Related PRs

# Testing
## Automated tests
- [ ] Unit Tests cover the change
- [ ] Smoke Tests cover the change  

## Steps to test or reproduce

# Deployment
## Strategy
- [ ] This is a standard deployment

## Migrations

Yes/No.

### CODE REVIEW

**Review by gaelsimon — APPROVED** [review]

**Comment by cdartnell-wgs** [comment]
[](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/Woosmap/openapi-specification/fix/addresses_per_page_depreciation/dist/woosmap-openapi3.json#tag/Localities-API/operation/localitiesDetails)

**Pull request merged**
